/**
 * Checked-in index of docs/active/ui-architecture-map.md.
 *
 * The prose document is the authority. This file is deliberately static: the
 * service schematic must never infer architecture from a live room snapshot.
 */
export type Stratum = "surface" | "machine" | "wire";

export interface MapNode {
  id: string;
  partNo: string;
  stratum: Exclude<Stratum, "wire">;
  group: string;
  title: string;
  see?: string;
  why: string;
  tie: string;
  ties: string[];
  terminals: string[];
  src: string;
  kind?: "dial";
}

export interface Terminal {
  id: string;
  field: string;
  status: "live" | "wish";
  phase?: string;
  consumers: string[];
}

export interface Gap {
  id: string;
  title: string;
  detail: string;
  filledBy?: string;
}

const DOC = "docs/active/ui-architecture-map.md";

export const MAP_NODES: MapNode[] = [
  {
    id: "s-01",
    partNo: "S-01",
    stratum: "surface",
    group: "CONSOLE · THE RIG",
    title: "Faceplate · Seated Voice",
    why: "Keeps the dial-seated immortal voice visible as the listening anchor.",
    tie: "The voice layer is stateless, survives every clear, and uses the spine as its mind.",
    ties: ["m-01", "r-08"],
    terminals: ["speakingPersona", "mood"],
    src: `${DOC} · FACEPLATE // CREW CHIEF UNIT`,
  },
  {
    id: "s-02",
    partNo: "S-02",
    stratum: "surface",
    group: "CONSOLE · THE RIG",
    title: "Second Voice Bay",
    why: "Makes a borrowed second voice visibly temporary, purposeful, and returnable.",
    tie: "The checked-out voice gets fresh context, settles a summary to the ticket, then dies.",
    ties: ["m-02", "r-08"],
    terminals: ["donnieCheckout", "speakingPersona"],
    src: `${DOC} · DONNIE BAY`,
  },
  {
    id: "s-03",
    partNo: "S-03",
    stratum: "surface",
    group: "CONSOLE · THE RIG",
    title: "The Spine · Rail",
    why: "Makes the room's durable memory a place: plans dock, craft pull work, conclusions bolt back on.",
    tie: "The task-manager spine is the room's only durable mind; tracker is index and repo is body.",
    ties: ["m-05", "m-06", "r-04"],
    terminals: ["plans", "crafts"],
    src: `${DOC} · THE SPINE // ENERGIZED RAIL`,
  },
  {
    id: "s-04",
    partNo: "S-04",
    stratum: "surface",
    group: "CONSOLE · THE RIG",
    title: "Plan Card",
    why: "Shows the ticket, progress, and process weight at a glance.",
    tie: "A plan is the durable ticket on the spine, and the gear tag is Dial 1's home.",
    ties: ["m-05", "r-07"],
    terminals: ["plans"],
    src: `${DOC} · PLAN CARD`,
  },
  {
    id: "s-05",
    partNo: "S-05",
    stratum: "surface",
    group: "CONSOLE · THE RIG",
    title: "Thread Node",
    why: "Shows whether a mortal orchestration thread is working, blocked, settling, or empty.",
    tie: "A node is a session, never the task; opening it is the live-thread form of tap-in.",
    ties: ["m-06", "r-04"],
    terminals: ["crafts", "focusCraftId", "artifacts"],
    src: `${DOC} · THREAD NODE + the open node`,
  },
  {
    id: "s-06",
    partNo: "S-06",
    stratum: "surface",
    group: "CONSOLE · THE RIG",
    title: "Salience Ring",
    why: "Answers how far this room is from needing you and shows the speak gate.",
    tie: "Instrument of the salience filter: speak now, queue for the lull, or log silently.",
    ties: ["m-03"],
    terminals: ["salience"],
    src: `${DOC} · SALIENCE RING`,
  },
  {
    id: "s-07",
    partNo: "S-07",
    stratum: "surface",
    group: "CONSOLE · THE RIG",
    title: "The Core · Spend",
    why: "Makes billing windows, current burn, and the tightest provider guard visible at one glance.",
    tie: "Cost honesty accompanies every brain escalation and voice clip; the Core is its desktop instrument.",
    ties: ["r-09"],
    terminals: ["spend"],
    src: `${DOC} · THE CORE`,
  },
  {
    id: "s-08",
    partNo: "S-08",
    stratum: "surface",
    group: "CONSOLE · THE RIG",
    title: "Reply Deck",
    why: "Puts text inject, push-to-talk, and held-question answers on one interpreter line.",
    tie: "All three inputs classify into command, question, new work, talk-back, or a one-off ask.",
    ties: ["m-04"],
    terminals: [
      "heldQuestion",
      "micHot",
      "grantArmed",
      "grantCountdown",
      "composerText",
      "focusCraftId",
    ],
    src: `${DOC} · REPLY DECK`,
  },
  {
    id: "s-09",
    partNo: "S-09",
    stratum: "surface",
    group: "CONSOLE · THE RIG",
    title: "Watch-Order Chips",
    why: "Makes a spoken subscription visible and gives it an equally visible stand-down phrase.",
    tie: "The existing live-mode subscription is the near neighbour of gated watcher threads, not the same thing.",
    ties: ["m-11"],
    terminals: ["crafts", "liveClip"],
    src: `${DOC} · WATCH-ORDER CHIPS`,
  },
  {
    id: "s-10",
    partNo: "S-10",
    stratum: "surface",
    group: "CONSOLE · THE RIG",
    title: "Verb Rack",
    why: "Shows the room's learned vocabulary and keeps deletion and consent visible.",
    tie: "Saved verbs live in the spine as versioned files; naming is consent and silent growth is forbidden.",
    ties: ["m-08", "m-11"],
    terminals: ["verbs"],
    src: `${DOC} · VERB RACK`,
  },
  {
    id: "s-11",
    partNo: "S-11",
    stratum: "surface",
    group: "CONSOLE · THE RIG",
    title: "Turn Chip",
    why: "Prints the brain and price of this turn and exposes tap-in classification.",
    tie: "Dial 3 is a configured routing table, not model judgment; every escalation is a costed event.",
    ties: ["m-04", "r-09"],
    terminals: ["turnChip", "tapIn"],
    src: `${DOC} · TURN CHIP`,
  },
  {
    id: "s-12",
    partNo: "S-12",
    stratum: "surface",
    group: "CONSOLE · THE RIG",
    title: "Crew Manifest",
    why: "Shows which personas are piloting craft and which are back on the rack.",
    tie: "The room manifest defines one lead and alternates; personas are character plus spine access, not a chatter set.",
    ties: ["m-10", "m-06"],
    terminals: ["crew", "crafts"],
    src: `${DOC} · CREW MANIFEST`,
  },
  {
    id: "s-13",
    partNo: "S-13",
    stratum: "surface",
    group: "CONSOLE · THE RIG",
    title: "Dock Mini Bar",
    why: "Carries the worst room's ambient status while you work somewhere else.",
    tie: "It is the smallest salience magnification and preserves the one-sentence-at-the-lull restraint.",
    ties: ["m-03", "m-01"],
    terminals: ["salience", "dockTicker", "dockLedRed", "mood", "speakingPersona", "fleet.rooms"],
    src: `${DOC} · DOCK MINI BAR`,
  },
  {
    id: "s-14",
    partNo: "S-14",
    stratum: "surface",
    group: "CONSOLE · THE RIG",
    title: "Long-Range Plot",
    why: "Turns salience into range: anything near you is close to needing you.",
    tie: "A blip is the same mortal craft as a rail node; one-offs have no ticket conduit and die on delivery.",
    ties: ["m-03", "m-06", "r-04"],
    terminals: ["crafts", "salience", "view"],
    src: `${DOC} · LONG-RANGE PLOT`,
  },
  {
    id: "f-01",
    partNo: "F-01",
    stratum: "surface",
    group: "FIELD UNIT · SIX HOUSINGS",
    title: "FIELD · Glance",
    why: "Answers whether anything is on fire in two seconds, from the pocket.",
    tie: "Phone-scale salience, with other rooms attributed rather than rendered.",
    ties: ["m-03", "m-06"],
    terminals: ["salience", "crafts", "audio", "clock", "fleet.rooms", "fleet.traffic"],
    src: `${DOC} · Mobile 1 · GLANCE`,
  },
  {
    id: "f-02",
    partNo: "F-02",
    stratum: "surface",
    group: "FIELD UNIT · SIX HOUSINGS",
    title: "FIELD · Answer",
    why: "Unblocks a held thread from the couch without opening the laptop.",
    tie: "A needs-feedback operator gate answered by exact option id, with the inject bound to the ticket.",
    ties: ["m-04", "m-06"],
    terminals: [
      "heldQuestion",
      "focusCraftId",
      "crafts",
      "transcript",
      "grantArmed",
      "grantCountdown",
    ],
    src: `${DOC} · Mobile 2 · ANSWER`,
  },
  {
    id: "f-03",
    partNo: "F-03",
    stratum: "surface",
    group: "FIELD UNIT · SIX HOUSINGS",
    title: "FIELD · Listen",
    why: "Makes who is talking, where audio is routed, and the free STOP action unmistakable.",
    tie: "The audio path and single speaker gate, with queued-for-lull as the salience filter's middle outcome.",
    ties: ["m-01", "m-02", "m-03"],
    terminals: [
      "speakingPersona",
      "donnieCheckout",
      "audio",
      "transcript",
      "queuedForLull",
      "crafts",
      "liveClip",
      "mood",
    ],
    src: `${DOC} · Mobile 3 · LISTEN`,
  },
  {
    id: "f-04",
    partNo: "F-04",
    stratum: "surface",
    group: "FIELD UNIT · SIX HOUSINGS",
    title: "FIELD · Start",
    why: "Starts real work or asks the room a cheap question by voice.",
    tie: "Shows the interpreter's fan-out explicitly, including ticket creation, spawning, and saved verbs.",
    ties: ["m-04", "m-05", "m-08"],
    terminals: ["tapIn", "transcript", "crafts", "verbs", "fleet.commission"],
    src: `${DOC} · Mobile 4 · START`,
  },
  {
    id: "f-05",
    partNo: "F-05",
    stratum: "surface",
    group: "FIELD UNIT · SIX HOUSINGS",
    title: "FIELD · Gauges",
    why: "Carries spend awareness away from the desk without allowing pocket-dial changes.",
    tie: "The Core's cost-honesty story plus read-only indexes to all three architectural dials.",
    ties: ["r-07", "r-08", "r-09"],
    terminals: ["spend", "turnChip"],
    src: `${DOC} · Mobile 5 · GAUGES`,
  },
  {
    id: "f-06",
    partNo: "F-06",
    stratum: "surface",
    group: "FIELD UNIT · SIX HOUSINGS",
    title: "FIELD · Dock + PTT",
    why: "Keeps type-or-speak input in one thumb-reachable place on every screen.",
    tie: "The mobile interpreter entry point; it never fakes a hot mic and replay never re-bills.",
    ties: ["m-04", "m-01"],
    terminals: ["composerText", "micHot", "speakingPersona", "donnieCheckout", "mood"],
    src: `${DOC} · FIELD DOCK + PTT pill`,
  },
  {
    id: "m-01",
    partNo: "M-01",
    stratum: "machine",
    group: "VOICE · IMMORTAL / STATELESS",
    title: "Mikey · Crew Chief",
    why: "Provides one continuous room voice without becoming another durable context window.",
    tie: "Immortal because stateless; catches up from the spine instead of session memory.",
    ties: ["s-01", "s-13", "f-03", "f-06", "m-03", "m-04"],
    terminals: ["speakingPersona", "mood", "transcript"],
    src: `${DOC} · The 60-second architecture`,
  },
  {
    id: "m-02",
    partNo: "M-02",
    stratum: "machine",
    group: "VOICE · IMMORTAL / STATELESS",
    title: "Checked-out Voice",
    why: "Provides one temporary specialist voice for one purpose.",
    tie: "Fresh context, written settlement, then death; never a multi-agent huddle.",
    ties: ["s-02", "f-03", "r-08"],
    terminals: ["donnieCheckout", "speakingPersona"],
    src: `${DOC} · DONNIE BAY`,
  },
  {
    id: "m-03",
    partNo: "M-03",
    stratum: "machine",
    group: "VOICE · IMMORTAL / STATELESS",
    title: "Salience Filter",
    why: "Prevents the room from becoming a chatterbox while preserving urgent interruption.",
    tie: "One gate chooses speak now, queue for lull, or log silently across the fleet.",
    ties: ["s-06", "s-13", "s-14", "f-01", "f-03", "m-01"],
    terminals: ["salience", "queuedForLull", "fleet.traffic", "fleet.threshold"],
    src: `${DOC} · SALIENCE RING`,
  },
  {
    id: "m-04",
    partNo: "M-04",
    stratum: "machine",
    group: "VOICE · IMMORTAL / STATELESS",
    title: "Interpreter Line",
    why: "Turns human input into an auditable command, question, new-work, talk-back, or one-off route.",
    tie: "One classifier feeds the command service and cheap tap-in path; it does not hide routing magic.",
    ties: ["s-08", "s-11", "f-02", "f-04", "f-06", "m-01", "m-05"],
    terminals: ["heldQuestion", "turnChip", "tapIn", "transcript", "composerText", "micHot"],
    src: `${DOC} · REPLY DECK`,
  },
  {
    id: "m-05",
    partNo: "M-05",
    stratum: "machine",
    group: "SPINE · THE ONLY DURABLE MIND",
    title: "Spine · GH Issues + Repo",
    why: "Keeps task truth durable outside every mortal context window.",
    tie: "Tracker is index, repo docs are body, transcripts are raw history, and conclusions settle back.",
    ties: ["s-03", "s-04", "f-04", "m-04", "m-06", "m-08", "m-09", "m-10"],
    terminals: ["plans", "artifacts", "verbs", "fleet.rooms"],
    src: `${DOC} · THE SPINE // ENERGIZED RAIL`,
  },
  {
    id: "m-08",
    partNo: "M-08",
    stratum: "machine",
    group: "SPINE · THE ONLY DURABLE MIND",
    title: "Saved Verbs",
    why: "Turns repeated spoken work into explicit, inspectable, deletable tools.",
    tie: "Verb files are versioned in the spine and can only be saved with named consent.",
    ties: ["s-10", "f-04", "m-05", "m-11"],
    terminals: ["verbs"],
    src: `${DOC} · VERB RACK`,
  },
  {
    id: "m-09",
    partNo: "M-09",
    stratum: "machine",
    group: "SPINE · THE ONLY DURABLE MIND",
    title: "Artifacts",
    why: "Lets mortal work leave inspectable output that can be kept, discarded, or settled.",
    tie: "Artifacts belong to craft while pending and become durable only through the spine.",
    ties: ["s-05", "m-05", "m-06"],
    terminals: ["artifacts", "crafts"],
    src: `${DOC} · THREAD NODE + the open node`,
  },
  {
    id: "m-10",
    partNo: "M-10",
    stratum: "machine",
    group: "SPINE · THE ONLY DURABLE MIND",
    title: "Room Manifests",
    why: "Makes rooms configuration rather than new architecture.",
    tie: "A manifest declares cast, spine pointer, gear default, brain table, and connectors.",
    ties: ["s-12", "m-05", "r-07", "r-08", "r-09"],
    terminals: ["fleet.rooms", "fleet.activeRoomId", "fleet.commission"],
    src: `${DOC} · CREW MANIFEST`,
  },
  {
    id: "m-06",
    partNo: "M-06",
    stratum: "machine",
    group: "MORTAL · PULL / SETTLE / DIE",
    title: "Build Threads",
    why: "Pull work from the spine, orchestrate silent workers, settle conclusions, and die.",
    tie: "The session is mortal and replaceable; the plan is durable and survives it.",
    ties: ["s-03", "s-05", "s-12", "s-14", "f-01", "f-02", "m-05", "m-07", "m-09"],
    terminals: ["crafts", "plans", "fleet.Craft.roomId"],
    src: `${DOC} · THREAD NODE + the open node`,
  },
  {
    id: "r-04",
    partNo: "R-04",
    stratum: "machine",
    group: "MORTAL · PULL / SETTLE / DIE",
    title: "One-Off Rule",
    why: "Allows useful disposable work without manufacturing a durable ticket.",
    tie: "No ticket, no conduit, and death on delivery; scratch rooms write no manifest.",
    ties: ["s-03", "s-05", "s-14", "m-06"],
    terminals: ["crafts", "fleet.rooms", "fleet.commission"],
    src: `${DOC} · LONG-RANGE PLOT`,
  },
  {
    id: "m-11",
    partNo: "M-11",
    stratum: "machine",
    group: "MORTAL · PULL / SETTLE / DIE",
    title: "Watchers · GATED #75",
    see: "NOT YET LIVE",
    why: "Would watch durable conditions and raise only meaningful changes.",
    tie: "Watcher threads stay gated until the spine is validated; watch orders are the existing nearby shape.",
    ties: ["s-09", "s-10", "m-08"],
    terminals: ["verbs", "crafts", "liveClip"],
    src: `${DOC} · WATCH-ORDER CHIPS`,
  },
  {
    id: "m-07",
    partNo: "M-07",
    stratum: "machine",
    group: "MORTAL · PULL / SETTLE / DIE",
    title: "Silent Workers",
    why: "Do subordinate work without opening more voices in the room.",
    tie: "Workers report to a mortal orchestration thread; they never talk to the operator directly.",
    ties: ["m-06"],
    terminals: ["crafts"],
    src: `${DOC} · The 60-second architecture`,
  },
  {
    id: "r-07",
    partNo: "R-07",
    stratum: "machine",
    group: "THREE DIALS · PHYSICAL CONTROLS",
    title: "Dial 1 · Ceremony",
    why: "Chooses how much process a thread runs without changing what a room is.",
    tie: "Bare, light, or full ceremony is stamped on the plan card and defaulted by the room manifest.",
    ties: ["s-04", "f-05", "m-10"],
    terminals: ["plans", "fleet.commission"],
    src: `${DOC} · PLAN CARD`,
    kind: "dial",
  },
  {
    id: "r-08",
    partNo: "R-08",
    stratum: "machine",
    group: "THREE DIALS · PHYSICAL CONTROLS",
    title: "Dial 2 · Voice",
    why: "Chooses who speaks without confusing persona with model weights.",
    tie: "Its visible home is the faceplate; a checkout is the one allowed second voice.",
    ties: ["s-01", "s-02", "f-05", "m-01", "m-02", "m-10"],
    terminals: ["speakingPersona", "donnieCheckout", "fleet.commission"],
    src: `${DOC} · FACEPLATE // CREW CHIEF UNIT`,
    kind: "dial",
  },
  {
    id: "r-09",
    partNo: "R-09",
    stratum: "machine",
    group: "THREE DIALS · PHYSICAL CONTROLS",
    title: "Dial 3 · Brain Tier",
    why: "Chooses the configured brain for one turn and makes its cost legible.",
    tie: "A routing table, not judgment; the turn chip is its receipt and visible home.",
    ties: ["s-07", "s-11", "f-05", "m-10"],
    terminals: ["turnChip", "spend", "fleet.commission"],
    src: `${DOC} · TURN CHIP`,
    kind: "dial",
  },
];

export const TERMINALS: Terminal[] = [
  { id: "view", field: "view", status: "live", consumers: ["s-14"] },
  {
    id: "mood",
    field: "mood",
    status: "live",
    consumers: ["s-01", "s-13", "f-03", "f-06", "m-01"],
  },
  {
    id: "focusCraftId",
    field: "focusCraftId",
    status: "live",
    consumers: ["s-05", "s-08", "f-02"],
  },
  {
    id: "plans",
    field: "plans[]",
    status: "live",
    consumers: ["s-03", "s-04", "m-05", "m-06", "r-07"],
  },
  {
    id: "crafts",
    field: "crafts[]",
    status: "live",
    consumers: [
      "s-03",
      "s-05",
      "s-09",
      "s-12",
      "s-14",
      "f-01",
      "f-02",
      "f-03",
      "f-04",
      "m-06",
      "m-07",
      "m-09",
      "m-11",
      "r-04",
    ],
  },
  {
    id: "salienceDelta",
    field: "crafts[].salienceDelta",
    status: "wish",
    phase: "R-D",
    consumers: ["s-05", "s-06"],
  },
  {
    id: "heldQuestion",
    field: "heldQuestion",
    status: "live",
    consumers: ["s-08", "f-02", "m-04"],
  },
  { id: "spend", field: "spend", status: "live", consumers: ["s-07", "f-05", "r-09"] },
  {
    id: "salience",
    field: "salience",
    status: "live",
    consumers: ["s-06", "s-13", "s-14", "f-01", "m-03"],
  },
  {
    id: "verbs",
    field: "verbs[]",
    status: "live",
    consumers: ["s-10", "f-04", "m-05", "m-08", "m-11"],
  },
  { id: "artifacts", field: "artifacts[]", status: "live", consumers: ["s-05", "m-05", "m-09"] },
  {
    id: "donnieCheckout",
    field: "donnieCheckout",
    status: "live",
    consumers: ["s-02", "f-03", "f-06", "m-02", "r-08"],
  },
  { id: "micHot", field: "micHot", status: "live", consumers: ["s-08", "f-06", "m-04"] },
  { id: "grantArmed", field: "grantArmed", status: "live", consumers: ["s-08", "f-02"] },
  { id: "grantCountdown", field: "grantCountdown", status: "live", consumers: ["s-08", "f-02"] },
  {
    id: "turnChip",
    field: "turnChip",
    status: "live",
    consumers: ["s-11", "f-05", "m-04", "r-09"],
  },
  {
    id: "transcript",
    field: "transcript[]",
    status: "live",
    consumers: ["f-02", "f-03", "f-04", "m-01", "m-04"],
  },
  { id: "tapIn", field: "tapIn", status: "live", consumers: ["s-11", "f-04", "m-04"] },
  { id: "crew", field: "crew[]", status: "live", consumers: ["s-12"] },
  { id: "clock", field: "clock", status: "live", consumers: ["f-01"] },
  { id: "rev", field: "rev", status: "live", consumers: [] },
  { id: "liveClip", field: "liveClip", status: "live", consumers: ["s-09", "f-03", "m-11"] },
  {
    id: "composerText",
    field: "composerText",
    status: "live",
    consumers: ["s-08", "f-06", "m-04"],
  },
  {
    id: "speakingPersona",
    field: "speakingPersona",
    status: "live",
    consumers: ["s-01", "s-02", "s-13", "f-03", "f-06", "m-01", "m-02", "r-08"],
  },
  { id: "dockTicker", field: "dockTicker", status: "live", consumers: ["s-13"] },
  { id: "dockLedRed", field: "dockLedRed", status: "live", consumers: ["s-13"] },
  { id: "audio", field: "audio", status: "live", consumers: ["f-01", "f-03"] },
  { id: "queuedForLull", field: "queuedForLull[]", status: "live", consumers: ["f-03", "m-03"] },
  { id: "fleet.zoom", field: "fleet.zoom", status: "wish", phase: "P1", consumers: [] },
  {
    id: "fleet.activeRoomId",
    field: "fleet.activeRoomId",
    status: "wish",
    phase: "P1",
    consumers: ["m-10"],
  },
  {
    id: "fleet.rooms",
    field: "fleet.rooms[] · RoomBerth",
    status: "wish",
    phase: "P1",
    consumers: ["s-13", "f-01", "m-03", "m-05", "m-10", "r-04"],
  },
  {
    id: "fleet.traffic",
    field: "fleet.traffic[] · belowGate",
    status: "wish",
    phase: "P1",
    consumers: ["f-01", "m-03"],
  },
  {
    id: "fleet.audioFloor",
    field: "fleet.audioFloor",
    status: "wish",
    phase: "P1",
    consumers: ["m-01", "m-03"],
  },
  {
    id: "fleet.threshold",
    field: "fleet.threshold",
    status: "wish",
    phase: "P1",
    consumers: ["m-03"],
  },
  {
    id: "fleet.commission",
    field: "fleet.commission · CommissionDraft",
    status: "wish",
    phase: "P2",
    consumers: ["f-04", "m-10", "r-04", "r-07", "r-08", "r-09"],
  },
  {
    id: "fleet.Craft.roomId",
    field: "Craft.roomId",
    status: "wish",
    phase: "P1",
    consumers: ["m-06"],
  },
];

export const GAPS: Gap[] = [
  {
    id: "gap-1",
    title: "RIVET 1 · ALL-PROJECTS VIEW",
    detail:
      "The Hangar now supplies project switching, cross-room attribution, and the one global audio floor.",
    filledBy: "ROUND D",
  },
  {
    id: "gap-2",
    title: "RIVET 2 · CORE ↔ GAUGES",
    detail: "The Core and FIELD Gauges still tell one spend story in two visual languages.",
  },
];

export const PART_TITLES = Object.fromEntries(
  MAP_NODES.map((node) => [node.partNo, node.title]),
) as Record<string, string>;

export function nodeByPartNo(partNo: string | null): MapNode | undefined {
  if (!partNo) return undefined;
  return MAP_NODES.find((node) => node.partNo.toLowerCase() === partNo.toLowerCase());
}
